### ISSUE TITLE
Adding Remarks Component

### ISSUE THREAD

**Issue by msaichaitanya735** [coding-Studio-vbit/A.R.M.A#14]
Add a new column of Remark in the Table of HOD
Add a button to enter the remark of particular letter in each row.

**Comment by Saravanan-Jodavula** [comment]
@Vishnu-19 I'm assigning this to you. Since we discussed about a different design, I think it'd be better if you do a mock-up first. Once the mockup is finalized, we can build the UI in no time I believe.
Try to make a mockup that's acheivable by using [react-bootstrap](https://react-bootstrap.github.io/components/) components.

**Comment by Saravanan-Jodavula** [comment]
@Vishnu-19 you can send your data to `/requestcreate` endpoint using `put` request for implementing remarks component. 
**Note :** Before sending the remarks component, you should get the row of the respective request and change _only_ remarks value and send it to `put` endpoint. You should send the remaining values which you fetched without changed. Also, approved students and approved facilities arrays can be added as properties in the `request_data` property of the data you fetch from request table.
